### PR TITLE
Ruby on Rails example app

### PR DESCRIPTION
**Pull request by Panczo**
Hi 
I have recently written application using ReactFineUploader with my rails app. I had made example app and i thought this example app would be great for others rails developers.
I was using rails with carrierwave in order to handle files in the backend. 
For my view layer i was using react from react_webpack_rails gem.

Best

### CODE REVIEW

**Comment by rnicholus** [comment]
Hey, wow, lots of work went into this. I think it would be best if we put this into a dedicated repository under the Fine Uploader organization. How does that sound? After this is moved, we can talk about additional changes before this is published for other rails developers to benefit from.

**Comment by Panczo** [comment]
Yes, of course, it's great idea.
And what do you mean by additional changes ? :)

**Comment by rnicholus** [comment]
What I mean by "additional changes" is that I haven't taken the opportunity to review your code yet, so I might have other suggestions once this is moved to a new repo. I'll create a new one shortly.

**Comment by Panczo** [comment]
@rnicholus I improved rails with reactfineuploader example app. You can grab it from [repo url](https://github.com/Panczo/reactfineuploader-example.git) and put it under Fine Uploader organization.

**Comment by rnicholus** [comment]
I can certainly do that, or to avoid simply copying the repo, would you be interested in transferring it into the FineUploader organization? I would make you the admin of the repo, of course.

**Comment by Panczo** [comment]
Ok no problem, i can transfer it to FineUploader organization.

**Comment by rnicholus** [comment]
Great! I just invited you to the Fine Uploader "transfer" organization. Because GitHub's permissions system is inherently flawed and transferring a repo in requires providing "god" access to the entire org, I created an intermediary org for this purpose. Once your repo is transferring into the transfer org, I'll transfer it on to @FineUploader and then give you admin access to the repo.

**Comment by rnicholus** [comment]
moved to https://github.com/FineUploader/react-fine-uploader-rails

**Pull request closed without merging**
