### PR TITLE
print_r removal to avoid server 500 error

### PR DESCRIPTION
**Pull request by rolandtoth**

### CODE REVIEW

**Comment by rnicholus** [comment]
Can you explain how this may cause the server to return a 500 response?

**Comment by rolandtoth** [comment]
I simply dump form post data after successful validation (development phase). I haven't investigated this deeper but removing print_r solved it.

**Comment by mrtnzlml** [comment]
:+1: It's just unexpected output. I think @rolandtoth is right.

**Comment by rnicholus** [comment]
It's really not clear to my why this line must be commented out. If it is causing a specific issue, I'd be glad to re-open this pull request, given an explanation of the problem and reason for the cause.

**Comment by rnicholus** [comment]
Also, I'm using this handler in my development server without any obvious issues.

**Comment by mrtnzlml** [comment]
I actually don't know the @rolandtoth use case, but I don't know why are you trying to keep something unnecessary in this code.

Well it's actually very simple. In modern frameworks you can use handle methods for AJAX handling:

```php
public function handleTest() {
	print_r('not useful');
	$this->sendJson(['success' => 'Success Response.']);
}
```

There are two problems with this code. At first, you get PHP Notice (`PHP User Notice: Possible problem: you are sending a HTTP header while already having some data in output buffer. Try Tracy\OutputDebugger or start session earlier.`) which make sense. Let's say it's fine, because it's just a notice. Unfortunately you got invalid JSON output as response for (for example) uploader...

Again, I don't know the original use case nor the added value with this output, I just see potential problem...

**Comment by rnicholus** [comment]
Thanks for your comment. I was looking for an explanation of the specific problem associated with this statement. Now that I have this, I'll happily merge in this pull request.

**Comment by rnicholus** [comment]
The PHP example will be further updates as part of 5.2, most likely in the next week or two.

**Comment by rolandtoth** [comment]
Thanks for the merge @rnicholus, and for the explanation, @mrtnzlml.

**Pull request merged**
