### PR TITLE
Changed string-binary types where functions required it.

### PR DESCRIPTION
**Pull request by andresespinosapc**
I was getting errors like "Given 'str' where 'byte' was expected". Using encode() and decode() functions I converted strings into byte-arrays and viceversa where it was needed.

### CODE REVIEW

**Comment by rnicholus** [comment]
Is this a Python 2 vs Python 3 issue? I gather you are using Python 3. What about those who are stuck w/ Python 2?

**Comment by andresespinosapc** [comment]
Sorry, I didn't noticed it. I don't have time right now to test it in Python 2 and create a solution for both versions, but when I can I'll do it.

**Comment by rnicholus** [comment]
Ok, I'll hold off on this until both Python 2 & 3 are able to be supported, especially since Python 2 seems to be more widely used. I suspect the current implementation does work in Python 2.

**Comment by rnicholus** [comment]
we should have a p3 example now

**Pull request closed without merging**
