### PR TITLE
Fixed: uploading '.xlsx' or '.docx' gets corrupt

### PR DESCRIPTION
**Pull request by KoenRijpstra**
Uploading a '.xlsx' or '.docx' corrupted the file and made it exactly 1024 KB.
I fixed the problem with the help of the following stackoverflow post: http://stackoverflow.com/questions/13726584/uploading-xlsx-or-docx-to-sharepoint-2007-from-asp-net-app-causing-file-c

### CODE REVIEW

**Comment by Drewman36** [comment]
Does anyone know if this plays well with Office 365 SharePoint? If not, is there another script that would be more conducive to O365 SharePoint to get the same results?

**Comment by rnicholus** [comment]
@Drewman36 What do you mean by "plays well"? What _specifically_ are you trying to do that involves Office Sharepoint?

**Comment by Drewman36** [comment]
I have a large amount of files that I would like to upload using a multi-document uploader into a Doc library that resides in Office 365. I have tried various ones located on CodePlex however in the last year Microsoft has changed the authentication and these utilities no longer work. What i would like to do is run a script that says look in this folder and upload these files to this doc library in O365. I have tried SP scripts as well no luck. Microsoft has allowed third parties to capitalize in this area of O365 from what I have seen so far.

**Comment by rnicholus** [comment]
It sound like you are looking for a server-side tool. Fine Uploader is a browser-based JavaScript uploader.

**Comment by Drewman36** [comment]
Actually I'm looking for a client side tool that being the admin i can run instead of "open in explorer" and drag and drop documents it takes too long that way. However browser based may work. I couldn't find the "how it works" of this app or any other instructions. Can you send them to me ? or post them?

**Comment by rnicholus** [comment]
Start at http://fineuploader.com. There are links to demos, a feature list, and full documentation from there.

**Comment by Drewman36** [comment]
Ok cool! Thanks Man!

**Pull request closed without merging**
